/* $Change: 431318 $ */
//
// Copyright (c) 2011 Samsung Electronics Co., Ltd.
// All rights reserved.

// This software contains confidential and proprietary information
// of Samsung Electronics Co., Ltd.
// The user of this software agrees not to disclose, disseminate or copy such
// Confidential Information and shall use the software only in accordance with
// the terms of the license agreement the user entered into with Samsung.
//
/**
 * @file		FTestStressTestCase.h
 * @brief		This is the header file for the %StressTestCase class.
 *
 * This header file contains the declarations of the %StressTestCase class.
 */
#ifndef _FTEST_STRESS_TEST_CASE_H_
#define _FTEST_STRESS_TEST_CASE_H_

#include "FTestTestCase.h"

namespace Osp { namespace Test {

class TestResult;

/**
 * @class		StressTestCase
 * @brief		This class implements a stress testcase.
 * @since		1.1
 *
 * The %StressTestCase class implements a stress testcase. A stress test case is used to create an instance of TestCase class which can run their test n times.
 * Therefore, this class must have an instance of another TestCase to run n times. @n
 *
 * For more information on the class features, see <a href="../com.osp.documentation.help/html/dev_env/testing_using_test_namespace.htm">Testing Applications Using the Test Namespace</a>.
 * 
 * Note that instead of this class, you can also use the helper macros, such as STRESS_TEST()  and NEW_STRESS_TEST_WITH_FIXTURE().
 *
 * The following example demonstrates how to use the %StressTestCase class.
 *
 * @code
 *
 * class TestBankAccount: public Osp::Test::TestFixture{
 *	public:
 *		void SetUpBeforeTestSuite() {}
 *		void TearDownAfterTestSuite() {}
 *		void SetUp() {pAccount = new BankAccount();}
 *		void TearDown() {delete pAccount;}
 *
 *		void TestStressDeposit() { pAccount->Deposit(100);}
 * };
 * ...
 * TestCase* testcase = new StressTestCase(new SimpleTestCase<TestBankAccount>("TestStressDeposit", &TestBankAccount::TestStressDeposit), 10);
 * testcase->Execute(&testResult);
 * ...
 * @endcode
 *
 * The following example demonstrates how to <a href="../com.osp.documentation.help/html/dev_env/test_macros.htm">use the helper macros</a> instead.
 *
 * @code
 * TestCase* testcase = NEW_STRESS_TEST_WITH_FIXTURE(TestBankAccount, TestStressDeposit, 10);
 * testcase->Execute(&testResult);
 * @endcode
 *
 * Also you can use STRESS_TEST Macro in the block which is generated by the bada Test Case Wizard. @n
 *
 * @code
 *  class TestBankAccount: public Osp::Test::TestFixture{
 *	TESTSUITE_BEGIN(TestBankAccount)
 *	STRESS_TEST(TestStressDeposit, 10)
 *	TESTSUITE_END()
 *    ...
 * @endcode
 *
 *
 */
class StressTestCase : public TestCase
{
public:
	/**
	 * Initializes the test case with the specified parameters including the test information.
	 *
	 * @since			1.1
	 * @param[in]	testCase		The test case to run 'n' number of times
	 * @param[in]	repeatedCount			The count to be repeated
	 * @param[in]	filePath			The file's path that creates this test case
	 * @param[in]	lineNum				The line number in the file that creates this test case
	 */
	StressTestCase(const TestCase& testCase, int repeatedCount = 1, const Osp::Base::String& filePath=__FILE__, int lineNum=__LINE__);

	/**
	 * This is the destructor for this class.
	 *
	 * @since			1.1
	 */
	virtual ~StressTestCase(void);

	/** @internal
	 * Gets the TestFixture to be used in this class.
	 *
	 * @since			1.1
	 * @return		the pointer on TestFixture
	 */
	virtual TestFixture* GetTestFixture(void)
	{
		return __pTestCase->GetTestFixture();
	}

private:
	virtual void Run(void);

protected:
    /**
     *@internal
     * This variable is for internal use only. The bada platform team is not
     * responsible for any behavioral correctness, consistency, and
     * security-related issues that might arise after using this variablevariable.
     *    
     * @since 1.1 
     */
	TestCase* __pTestCase;	
    /**
     *@internal
     * This variable is for internal use only. The bada platform team is not
     * responsible for any behavioral correctness, consistency, and
     * security-related issues that might arise after using this variablevariable.
     *     * @since 1.1 
     */
	int __repeatedCount;
};

}}
#endif /* _FTEST_STRESS_TEST_CASE_H_ */
