/* $Change: 1114438 $ */
#ifndef _gl2_macro_h_
#define _gl2_macro_h_

#define		glActiveTexture			glActiveTexture_2
#define		glAttachShader			glAttachShader_2
#define		glBindAttribLocation	glBindAttribLocation_2
#define		glBindBuffer			glBindBuffer_2
#define		glBindFramebuffer		glBindFramebuffer_2
#define		glBindRenderbuffer		glBindRenderbuffer_2
#define		glBindTexture			glBindTexture_2
#define		glBlendColor			glBlendColor_2
#define		glBlendEquation			glBlendEquation_2
#define		glBlendEquationSeparate	glBlendEquationSeparate_2
#define		glBlendFunc				glBlendFunc_2
#define		glBlendFuncSeparate		glBlendFuncSeparate_2
#define		glBufferData			glBufferData_2
#define		glBufferSubData			glBufferSubData_2
#define		glCheckFramebufferStatus	glCheckFramebufferStatus_2
#define		glClear				glClear_2
#define		glClearColor		glClearColor_2
#define		glClearDepthf		glClearDepthf_2	
#define		glClearStencil		glClearStencil_2
#define		glColorMask		glColorMask_2
#define		glCompileShader		glCompileShader_2
#define		glCompressedTexImage2D		glCompressedTexImage2D_2
#define		glCompressedTexSubImage2D		glCompressedTexSubImage2D_2
#define		glCopyTexImage2D		glCopyTexImage2D_2
#define		glCopyTexSubImage2D		glCopyTexSubImage2D_2
#define		glCreateProgram		glCreateProgram_2
#define		glCreateShader		glCreateShader_2
#define		glCullFace		glCullFace_2
#define		glDeleteBuffers		glDeleteBuffers_2
#define		glDeleteFramebuffers		glDeleteFramebuffers_2
#define		glDeleteProgram		glDeleteProgram_2
#define		glDeleteRenderbuffers		glDeleteRenderbuffers_2
#define		glDeleteShader		glDeleteShader_2
#define		glDeleteTextures		glDeleteTextures_2
#define		glDepthFunc		glDepthFunc_2
#define		glDepthMask		glDepthMask_2
#define		glDepthRangef		glDepthRangef_2
#define		glDetachShader		glDetachShader_2
#define		glDisable		glDisable_2
#define		glDisableVertexAttribArray		glDisableVertexAttribArray_2
#define		glDrawArrays		glDrawArrays_2
#define		glDrawElements		glDrawElements_2
#define		glEnable		glEnable_2
#define		glEnableVertexAttribArray		glEnableVertexAttribArray_2
#define		glFinish		glFinish_2
#define		glFlush		glFlush_2
#define		glFramebufferRenderbuffer		glFramebufferRenderbuffer_2
#define		glFramebufferTexture2D		glFramebufferTexture2D_2
#define		glFrontFace		glFrontFace_2
#define		glGenBuffers		glGenBuffers_2
#define		glGenerateMipmap		glGenerateMipmap_2
#define		glGenFramebuffers		glGenFramebuffers_2
#define		glGenRenderbuffers		glGenRenderbuffers_2
#define		glGenTextures		glGenTextures_2
#define		glGetActiveAttrib		glGetActiveAttrib_2
#define		glGetActiveUniform		glGetActiveUniform_2
#define		glGetAttachedShaders		glGetAttachedShaders_2
#define		glGetAttribLocation		glGetAttribLocation_2
#define		glGetBooleanv		glGetBooleanv_2
#define		glGetBufferParameteriv		glGetBufferParameteriv_2
#define		glGetError		glGetError_2
#define		glGetFloatv		glGetFloatv_2
#define		glGetFramebufferAttachmentParameteriv		glGetFramebufferAttachmentParameteriv_2
#define		glGetIntegerv		glGetIntegerv_2
#define		glGetProgramiv		glGetProgramiv_2
#define		glGetProgramInfoLog		glGetProgramInfoLog_2
#define		glGetRenderbufferParameteriv		glGetRenderbufferParameteriv_2
#define		glGetShaderiv		glGetShaderiv_2
#define		glGetShaderInfoLog		glGetShaderInfoLog_2
#define		glGetShaderPrecisionFormat		glGetShaderPrecisionFormat_2
#define		glGetShaderSource		glGetShaderSource_2
#define		glGetString		glGetString_2
#define		glGetTexParameterfv		glGetTexParameterfv_2
#define		glGetTexParameteriv		glGetTexParameteriv_2
#define		glGetUniformfv		glGetUniformfv_2
#define		glGetUniformiv		glGetUniformiv_2
#define		glGetUniformLocation		glGetUniformLocation_2
#define		glGetVertexAttribfv		glGetVertexAttribfv_2
#define		glGetVertexAttribiv		glGetVertexAttribiv_2
#define		glGetVertexAttribPointerv		glGetVertexAttribPointerv_2
#define		glHint		glHint_2
#define		glIsBuffer		glIsBuffer_2
#define		glIsEnabled		glIsEnabled_2
#define		glIsFramebuffer		glIsFramebuffer_2
#define		glIsProgram		glIsProgram_2
#define		glIsRenderbuffer		glIsRenderbuffer_2
#define		glIsShader		glIsShader_2
#define		glIsTexture		glIsTexture_2
#define		glLineWidth		glLineWidth_2
#define		glLinkProgram		glLinkProgram_2
#define		glPixelStorei		glPixelStorei_2
#define		glPolygonOffset		glPolygonOffset_2
#define		glReadPixels		glReadPixels_2
#define		glReleaseShaderCompiler		glReleaseShaderCompiler_2
#define		glRenderbufferStorage		glRenderbufferStorage_2
#define		glSampleCoverage		glSampleCoverage_2
#define		glScissor		glScissor_2
#define		glShaderBinary		glShaderBinary_2
#define		glShaderSource		glShaderSource_2
#define		glStencilFunc		glStencilFunc_2
#define		glStencilFuncSeparate		glStencilFuncSeparate_2
#define		glStencilMask		glStencilMask_2
#define		glStencilMaskSeparate		glStencilMaskSeparate_2
#define		glStencilOp		glStencilOp_2
#define		glStencilOpSeparate		glStencilOpSeparate_2
#define		glTexImage2D		glTexImage2D_2
#define		glTexParameterf		glTexParameterf_2
#define		glTexParameterfv		glTexParameterfv_2
#define		glTexParameteri		glTexParameteri_2
#define		glTexParameteriv		glTexParameteriv_2
#define		glTexSubImage2D		glTexSubImage2D_2
#define		glUniform1i		glUniform1i_2
#define		glUniform2i		glUniform2i_2
#define		glUniform3i		glUniform3i_2
#define		glUniform4i		glUniform4i_2
#define		glUniform1f		glUniform1f_2
#define		glUniform2f		glUniform2f_2
#define		glUniform3f		glUniform3f_2
#define		glUniform4f		glUniform4f_2
#define		glUniform1iv		glUniform1iv_2
#define		glUniform2iv		glUniform2iv_2
#define		glUniform3iv		glUniform3iv_2
#define		glUniform4iv		glUniform4iv_2
#define		glUniform1fv		glUniform1fv_2
#define		glUniform2fv		glUniform2fv_2
#define		glUniform3fv		glUniform3fv_2
#define		glUniform4fv		glUniform4fv_2
#define		glUniformMatrix2fv		glUniformMatrix2fv_2
#define		glUniformMatrix3fv		glUniformMatrix3fv_2
#define		glUniformMatrix4fv		glUniformMatrix4fv_2
#define		glUseProgram		glUseProgram_2
#define		glValidateProgram		glValidateProgram_2
#define		glVertexAttrib1f		glVertexAttrib1f_2
#define		glVertexAttrib2f		glVertexAttrib2f_2
#define		glVertexAttrib3f		glVertexAttrib3f_2
#define		glVertexAttrib4f		glVertexAttrib4f_2
#define		glVertexAttrib1fv		glVertexAttrib1fv_2
#define		glVertexAttrib2fv		glVertexAttrib2fv_2
#define		glVertexAttrib3fv		glVertexAttrib3fv_2
#define		glVertexAttrib4fv		glVertexAttrib4fv_2
#define		glVertexAttribPointer		glVertexAttribPointer_2
#define		glViewport		glViewport_2
  
#endif // _egl2_macro_h_